bulak-smart-connect-js/src/App.jsx, bulak-smart-connect-js/src/pages/SignUpForm.jsx, bulak-smart-connect-js/src/styles/SignUpForm.css, package-lock.json
create folder
>pages 
- SignUpForm.jsx
>Styels
- SignUpForm.css
=> SignUpForm created

README.md, bsc-js-backend/.gitignore, bsc-js-backend/.prettierrc, bsc-js-backend/README.md, bsc-js-backend/eslint.config.mjs, bsc-js-backend/nest-cli.json, bsc-js-backend/package-lock.json, bsc-js-backend/package.json, bsc-js-backend/src/app.controller.spec.ts, bsc-js-backend/src/app.controller.ts, bsc-js-backend/src/app.module.ts, bsc-js-backend/src/app.service.ts, bsc-js-backend/src/main.ts, bsc-js-backend/test/app.e2e-spec.ts, bsc-js-backend/test/jest-e2e.json, bsc-js-backend/tsconfig.build.json, bsc-js-backend/tsconfig.json
added:
NestJS Backend Project Folder
changes:
README.md
=> NestJS Project Folder

bulak-smart-connect-js/src/AppointmentComponents/AppointmentContent.jsx, bulak-smart-connect-js/src/AppointmentComponents/AppointmentDashboard.jsx
added function that when user clicks a state in the calendar in the appointment dashboard it will direct to the appointment form and the selected date
=> edited appointment calendar

bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AccountManagement.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AdminAddAccount.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AdminAddAccount.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/SearchAdd.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/UserInfoCard.css, bulak-smart-connect-js/src/App.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/DataPrivacy.css, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/SignUpForm.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/UserNamePassword.css
=> Admin Add User Draft

bulak-smart-connect-js/package-lock.json, bulak-smart-connect-js/package.json, bulak-smart-connect-js/src/main.jsx
- Added react-scan dependency to package.json for easier debugging.
- Imported scan from react-scan in main.jsx before React and ReactDOM.
- Enabled scanning in main.jsx for debugging purposes (to be disabled in production).
=> feat: add react-scan for enhanced debugging capabilities

bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminMarriageLicensePreview.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminMarriageLicensePreview.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageCertificateForm.css, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx
debug duplicate marriage
still need to add cancel marriage application ( may error )
=> admin preview application

bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.jsx, bulak-smart-connect-js/src/NavigationComponents/NavSide.css, bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.css, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageSummaryForm.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/RecentApplicationsComponent.jsx
implementation of side nav ( w/ username & email like the nav in admin dashboard )
=> application status note visible to user

bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AccountManagement.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AdminAddAccount.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/NewUserInfo.js, bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/UserTable.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAnnouncementComponents/AnnouncementPost.css
EDIT user <ongoing> <debugging> please lord sana bukas okay na
=> delete user successful yehey HAHAHA

bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx, bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
=> fixed widdth admin dashboard

bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthcertificate.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/FileUpload.jsx
Request for copy or regular birth image upload in local storage
=> Modify form in all birth certificate type

bsc-js-backend/src/app.module.ts, bsc-js-backend/src/auth/auth.controller.spec.ts, bsc-js-backend/src/auth/auth.controller.ts, bsc-js-backend/src/auth/auth.service.spec.ts, bsc-js-backend/src/auth/auth.service.ts, bsc-js-backend/src/auth/dto/register.dto.ts, bsc-js-backend/src/auth/guards/roles.guard.ts, bsc-js-backend/src/auth/jwt.strategy.ts, bsc-js-backend/src/main.ts, bsc-js-backend/src/modules/queue/queue.controller.ts, bsc-js-backend/src/modules/queue/queue.gateway.ts, bsc-js-backend/src/modules/queue/queue.module.ts, bsc-js-backend/src/modules/queue/queue.service.ts, bsc-js-backend/src/users/entities/user.entity.ts
Enhance code clarity and maintainability across multiple files, including database connection setup and various service implementations.
=> Refactor code for improved readability and consistency

.github/workflows/code-quality-security.yml, bulak-smart-connect-js/package-lock.json, bulak-smart-connect-js/package.json, bulak-smart-connect-js/vite.config.js
Improve bundle analysis by adding workflows for frontend and backend, integrating source-map-explorer, and visualizing bundle sizes. Update dependencies and enhance code complexity reporting with ESLint integration.
=> Enhance bundle analysis and reporting workflows

bsc-js-backend/src/modules/queue/queue.controller.ts, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx, bulak-smart-connect-js/src/services/queueService.js
Improve queue creation by associating user IDs from JWT and refining guest handling in the WalkInForm. Refactor API requests to utilize a preconfigured axios instance for better maintainability.
=> Enhance queue creation and user identification logic

bsc-js-backend/docs/bulak-smart-connect-postman-collection.json, bsc-js-backend/docs/user-management-api.md, bsc-js-backend/docs/user-update-readme.md, bsc-js-backend/package-lock.json, bsc-js-backend/package.json, bsc-js-backend/src/auth/auth.controller.ts, bsc-js-backend/src/auth/auth.service.ts, bsc-js-backend/src/auth/dto/login.dto.ts, bsc-js-backend/src/auth/dto/register.dto.ts, bsc-js-backend/src/auth/dto/update-user.dto.ts, bsc-js-backend/src/main.ts, bsc-js-backend/src/modules/queue/dto/create-queue.dto.ts, bsc-js-backend/src/modules/queue/queue.module.ts, bsc-js-backend/src/modules/queue/queue.service.ts, bsc-js-backend/src/roles/roles.service.ts, bsc-js-backend/test/user-updates.e2e-spec.ts, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx, bulak-smart-connect-js/src/context/AuthContext.jsx, bulak-smart-connect-js/src/services/api.js
Refactor queue creation logic to track guest status and implement comprehensive user update features for both citizens and admins. This includes improved validation, error handling, and Swagger documentation for user management endpoints. Additionally, enhance global validation pipe configuration and add necessary DTOs for user updates.
=> Enhance user update functionality and queue management

bsc-js-backend/src/modules/queue/queue.controller.ts, bsc-js-backend/src/modules/queue/queue.module.ts, bsc-js-backend/src/modules/queue/queue.service.ts, bsc-js-backend/src/modules/queue/queues.controller.ts, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/AdminDashboard.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/WalkInQueueAdmin.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInQueueList.jsx, bulak-smart-connect-js/src/services/queueService.js
Introduce new endpoints for fetching and updating queue details, including bulk fetching and improved error handling for walk-in queues. Update the queue service to streamline API interactions.
=> Add endpoints for queue details and enhance walk-in queue fetching

bsc-js-backend/src/modules/queue/queue.controller.ts, bsc-js-backend/src/modules/queue/queue.service.ts, bsc-js-backend/src/modules/queue/queues.controller.ts, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminDashboard/WalkInQueueAdmin.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInDetails/AdminWalkInDetails.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx, bulak-smart-connect-js/src/services/queueService.js
Improve error handling and logging for queue status updates, ensuring consistent status mapping and better user feedback on failures.
=> Enhance queue status update functionality with improved error handling and logging

bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RecentAppointment.jsx, bulak-smart-connect-js/src/services/appointmentService.js
Reorganize appointment service methods and enhance logging. Integrate backend functionality for fetching and creating appointments, allowing for real-time availability updates.
=> Refactor appointment management and integrate real-time availability

bsc-js-backend/src/modules/queue/queue.controller.spec.ts, bsc-js-backend/src/modules/queue/queue.gateway.spec.ts, bsc-js-backend/src/modules/queue/queue.service.spec.ts, bsc-js-backend/src/modules/queue/queues.controller.spec.ts, bsc-js-backend/src/roles/roles.controller.spec.ts, bsc-js-backend/src/roles/roles.service.spec.ts
Introduce unit tests for the Queue, Queues, and Roles controllers and services, enhancing test coverage and ensuring proper functionality. Include mock implementations for dependencies in the tests.
=> Add unit tests for Queue, Queues, and Roles components

README.md
Enhance the README to include additional backend tables and detailed development scripts for both frontend and backend technologies. This update improves clarity and accessibility for developers.
=> Update README with backend tables and development scripts

README.md, bsc-js-backend/src/main.ts
Improve the README and Swagger documentation by adding detailed API features, authentication information, and additional guides for local development and API testing.
=> Enhance API documentation with Swagger details and guides

bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CTCBirthcertificate.jsx
Correct import paths for documentApplicationService and integrate it for backend application creation and status updates. Refactor the CopyBirthCertificate component to remove outdated backend logic.
=> Fix documentApplicationService integration and refactor component logic

bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointemtForm.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentDashboard.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QRCodeAppointment.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/QrCodeAppointment.css, bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RecentAppointment.jsx
added back / complete button in appointment summary
=> integration of FAB  Announce in the announcement

bulak-smart-connect-js/.gitignore, bulak-smart-connect-js/index.html, bulak-smart-connect-js/package-lock.json, bulak-smart-connect-js/package.json, bulak-smart-connect-js/src/App.jsx, bulak-smart-connect-js/src/components/InstallPrompt.jsx, bulak-smart-connect-js/src/components/OfflineIndicator.jsx, bulak-smart-connect-js/src/hooks/usePWA.js, bulak-smart-connect-js/vite.config.js
- Added vite-plugin-pwa to enable PWA features.
- Implemented InstallPrompt component to prompt users to install the app.
- Created OfflineIndicator component to notify users of online/offline status.
- Updated App component to include InstallPrompt and OfflineIndicator.
- Enhanced vite.config.js with PWA configuration and caching strategies.
- Introduced usePWA hook to manage PWA installation logic.
=> feat: add PWA support with install prompt and offline indicators

bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AccountManagement.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AccountManagement.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/ContactInformation.css, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/ContactInformation.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/DataPrivacy.css, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/DataPrivacy.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/SignUpForm.css, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/SignUpForm.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/UpdateCheckbox.css, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/UpdateCheckbox.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/UserNamePassword.jsx
-fixed signup-form
-fixed header of Admin Usermanagement
=> MODIFY signup and accountmanagement

bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthApplicationSummary.jsx
Update useEffect dependencies and conditionally load application data to prevent an infinite loop.
=> Fix infinite loop in data loading logic

bulak-smart-connect-js/src/App.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateForm/CopyBirthCertificate.jsx
Improve local storage management by integrating localStorageManager in the CopyBirthCertificate component and initializing it in the App component for monitoring and cleanup.
=> Refactor local storage handling in CopyBirthCertificate component

bsc-js-backend/src/modules/queue/queue.controller.ts, bulak-smart-connect-js/index.html
Refactor the QueueController to utilize the User decorator for authentication, simplifying user ID extraction. Correct a typo in the mobile web app capability meta tag in index.html.
=> Refactor QueueController and fix meta tag typo

bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AdminAddAccount.jsx
Enhance user form validation by making fields like username and contact number required, and update role display names for clarity.
=> Update user form validation and role display names in AdminAddUser component

bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminCopyBirthPreview.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminCopyBirthPreview.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/ApplicationAdminDashboard.jsx, bulak-smart-connect-js/src/NavigationComponents/NavSide.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.css, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationContent.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/ApplicationForm.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/BirthCertificateDashboard.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx
o	Statistics color
o	Status list color
=> •	ApplicationDashbard ( admin )

bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/RecentApplicationsComponent.jsx, bulak-smart-connect-js/src/services/documentApplicationService.js
Fetch user applications using a unified endpoint and enhance the application type display logic to manage missing data more effectively.
=> Integrate document application service and improve error handling

bulak-smart-connect-js/src/services/documentApplicationService.js
Update the `updateApplication` method to utilize the PATCH HTTP method instead of PUT, allowing for partial updates to the application data.
=> Change updateApplication method to use PATCH for partial updates

bsc-js-backend/src/modules/document-applications/document-applications.service.ts, bsc-js-backend/src/modules/document-applications/entities/application-status-history.entity.ts, bsc-js-backend/src/modules/document-applications/entities/document-application.entity.ts, bulak-smart-connect-js/src/services/documentApplicationService.js, database/modified-application-status-history-061325-v12/Dump20250613_Modified_Application_Status_History.sql, database/modified-document-applications-table-061325-v13/Dump20250613_Modified_Document_Applications_Table.sql
Sanitize filenames during uploads to remove emojis and special characters. Ensure non-nullable application relations in the ApplicationStatusHistory entity. Update application update method to prevent cascade issues and improve access checks. Add additional application statuses for better tracking and provide an initial SQL dump for the bulak_smart_connect database with complete table structures and sample data.
=> Enhance file upload and application status management

bsc-js-backend/src/modules/document-applications/services/minio.service.ts, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx, bulak-smart-connect-js/src/services/documentApplicationService.js
Improve file upload sanitization and logging in the document application service. Correct spelling in the mandatory documents list for the Marriage License application.
=> Enhance file upload sanitization and fix spelling in Marriage License application

bsc-js-backend/src/modules/document-applications/services/minio.service.ts
Simplify the file upload process by eliminating the sanitization of object names, allowing the original object name to be used directly. This change streamlines the upload functionality.
=> Refactor file upload process by removing object name sanitization

bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AdminAppointmentDashboard.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/AppointmentDetails.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/AppointmentDetails.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/UserInfoCard.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/UserInfoCard.jsx, bulak-smart-connect-js/src/App.jsx
Introduce functionality for fetching appointment data and generating charts in the AdminAppointmentDashboard. Improve filtering and formatting in AllAppointmentsAdmin, and enhance loading states and status updates in appointment details.
=> Implement appointment data fetching and enhance appointment handling

bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/RecentAppointment.jsx
Introduce a function to save recent appointments in the RecentAppointment component and format the appointment date before submission in the AppointmentContainer.
=> Add recent appointments functionality and date formatting

bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminSmartQueueComponents/ScreenSmartQueue.css, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminSmartQueueComponents/ScreenSmartQueue.jsx
without header<Bulak Smart Connect>,  show and get data from admin queue,
=> screen queue

bsc-js-backend/src/modules/queue/queue.service.ts, bsc-js-backend/src/modules/queue/queues.controller.ts, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInForm.jsx, bulak-smart-connect-js/src/services/queueService.js
Introduce functionality to fetch user-specific queues and queue details by ID. Enhance queue position logic and improve logging for better debugging. Reset form data for guests in the WalkInForm component.
=> Enhanced user queue fetching and management features

bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInQueue.css, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInQueueList.jsx
Improve the user experience by adding a serving status to the queue display and incorporating animation effects for better visibility. This update also includes a merge from the main branch.
=> Enhance queue display with serving status and animations

.github/workflows/update-dashboard.yml
Introduce a GitHub Actions workflow to automate the generation and deployment of the dashboard.
=> Add GitHub Actions workflow for dashboard generation and deployment

README.md
Introduce status badges for various GitHub Actions workflows in the README to provide real-time visibility into the CI/CD pipeline. Enhance the README with detailed descriptions of the workflows, their purposes, and access to a live dashboard for monitoring code quality and security.
=> Add GitHub Actions status badges and enhance README with CI/CD workflow details

bulak-smart-connect-js/package.json, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateForm/MarriageLicenseSummary.jsx, bulak-smart-connect-js/src/__tests__/BirthApplicationSummary.test.jsx, bulak-smart-connect-js/src/__tests__/ErrorBoundary.test.jsx, bulak-smart-connect-js/src/__tests__/MarriageCertificateForm.test.jsx, bulak-smart-connect-js/src/__tests__/applicationUtils.test.jsx, bulak-smart-connect-js/src/__tests__/usePWA.test.jsx, bulak-smart-connect-js/src/__tests__/userService.test.jsx, bulak-smart-connect-js/src/setupTests.js, bulak-smart-connect-js/vitest.config.js, bulak-smart-connect-js/vitest.integration.config.js
Add integration and unit tests for various components, refactor existing tests for clarity and error handling, and enhance test configurations including localStorage and matchMedia mocks.
=> Enhance testing framework and improve error handling

bsc-js-backend/src/modules/document-applications/entities/document-file.entity.ts, database/modified-document-applications-table-062725-v14/Dump20250627_Modified_Document_Applications_Table_V2.sql
Enhance the DocumentFile entity by updating the document_category column length for better data storage capabilities.
=> Increase document_category column length to 250 characters

bsc-js-backend/generate-hash.js, bsc-js-backend/src/auth/auth.service.ts, bsc-js-backend/src/modules/queue/queue.service.ts, bsc-js-backend/test/user-updates.e2e-spec.ts, bulak-smart-connect-js/src/AdminBulakSmartConnect/AccountManagementComponents/AdminAddAccount.jsx, bulak-smart-connect-js/src/LogInComponents/LogInCard.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/SignUpComponents/SignUpForm.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/UserAccountSettings/UserAccount.jsx, bulak-smart-connect-js/src/__tests__/LogInCard.test.jsx
Improve password validation by enforcing complexity requirements, including minimum length, uppercase, lowercase, numeric, and special characters. Refactor queue number generation to accurately count queues created today.
=> Refactor password validation and queue number generation

FRONTEND_SETUP_GUIDE.md, README.md, bulak-smart-connect-js/.env.example, bulak-smart-connect-js/.env.production.example, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAccount/AdminAccount.jsx, bulak-smart-connect-js/src/config/env.js
Eliminate the default storage prefix in environment configurations to allow for a more flexible setup.
=> Remove default storage prefix from environment configurations

bsc-js-backend/src/modules/queue/queue.controller.ts
Limit access to the manual daily reset and pending count endpoints to users with admin, super admin, or staff roles, while enhancing logging for unauthorized access attempts.
=> Restrict access to manual daily reset and pending count for privileged users

bsc-js-backend/src/auth/auth.controller.ts, bsc-js-backend/src/auth/dto/queue-notification.dto.ts, bsc-js-backend/src/services/email.service.ts, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminWalkInQueue/AdminWalkInQueue.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx, bulak-smart-connect-js/src/services/queueNotificationService.js
Introduce a new service for sending email notifications related to queue positions and status changes. Implement a DTO for notification data and enhance the AuthController to handle notification requests. Update the admin interface to trigger notifications when queue statuses change.
=> Add queue notification functionality with email alerts for position updates and status changes

bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAccount/AdminAccount.jsx, bulak-smart-connect-js/src/LogInComponents/LogInCard.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/UserAccountSettings/UserAccount.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/WalkInComponents/WalkInDashBoard.jsx, bulak-smart-connect-js/src/services/queueNotificationService.js
Improve the queue notification system with detailed logging and error handling. Enhance user email retrieval by integrating AuthContext and adding a localStorage fallback. Implement OTP verification for the password change process along with improved validation messages.
=> Enhance queue notifications, user email retrieval, and password change process

bsc-js-backend/src/auth/auth.controller.ts, bsc-js-backend/src/auth/dto/appointment-notification.dto.ts, bsc-js-backend/src/services/email.service.ts, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/AppointmentDetails.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/AppointmentComponents/AppointmentContent.jsx, bulak-smart-connect-js/src/services/appointmentNotificationService.js
Introduce an appointment notification service with a dedicated DTO for email notifications. Refactor existing code to integrate this service for sending status updates and confirmations, while improving validation and error handling. Enhance email lookup logic to ensure notifications are sent correctly.
=> Add appointment notification service and enhance email handling

bsc-js-backend/src/modules/appointment/appointment.controller.ts, bsc-js-backend/src/modules/appointment/appointment.service.ts, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminAppointmentDashboard/AllAppointmentsAdmin.jsx, bulak-smart-connect-js/src/AdminBulakSmartConnect/AppointmentDetailsComponents/AppointmentDetails.jsx, bulak-smart-connect-js/src/services/appointmentService.js
Improve appointment fetching by including user details and refining email retrieval logic. Enhance appointment matching and status update handling for better notification management.
=> Enhance appointment fetching and email handling

bsc-js-backend/src/auth/auth.controller.ts, bsc-js-backend/src/modules/document-applications/document-applications.controller.ts, bsc-js-backend/src/modules/document-applications/document-applications.service.ts, bsc-js-backend/src/services/email.service.ts, bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx, bulak-smart-connect-js/src/services/documentApplicationNotificationService.js, bulak-smart-connect-js/src/services/documentApplicationService.js
Enhance the document application service to support notifications for confirmation, status updates, approvals, and rejections. Include user relationships for admin notifications and improve error handling in email lookups. Update methods to fetch applications with user data for better notification management.
=> Implement document application notification system

bulak-smart-connect-js/src/AdminBulakSmartConnect/AdminApplicationComponents/AdminApplicationDetails.jsx
Improve the application status update process by adding detailed logging and enhanced email notifications. This includes better handling of applicant names and tailored notifications based on the application status.
=> Enhance application status update with detailed notifications and logging

bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/CorrectionChildSex.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedAbove18.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedBelow18.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOneParentForeigner.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/DelayedOutOfTown.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/BirthCertificateApplications/FirstNameCorrection.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageCertificateApplication.jsx, bulak-smart-connect-js/src/UserBulakSmartConnect/ApplicationComponents/MarriageCertificateApplications/MarriageLicenseApplication.jsx
Add functionality to send confirmation email notifications upon successful application submission across various registration types. This enhancement improves user experience by providing immediate feedback and confirmation of their application status.
=> Enhance application submission process with confirmation email notifications

BACKEND_SETUP_GUIDE.md, bsc-js-backend/.env.example, bsc-js-backend/.env.production.example, bsc-js-backend/src/app.module.ts
Introduce SSL configuration options for Aiven MySQL in environment files and update the app module to utilize these settings for secure database connections.
=> Add Aiven MySQL SSL configuration to environment files and app module

bsc-js-backend/src/main.ts
Introduce a health check endpoint to monitor the status of the database connection and the MinIO service, helping to prevent service spin-down on Render.
=> Add health check endpoint for database and MinIO status monitoring

bsc-js-backend/src/main.ts
Enhance the MinIO connection check to gracefully handle cases where the service is not configured or available, providing clearer status messages.
=> Improve MinIO connection check handling

README.md, bsc-js-backend/src/main.ts
Enhance the health check in the bootstrap process to handle database and MinIO service checks more gracefully, ensuring better error handling and clearer status reporting.
=> Refactor health check to improve service checks

bulak-smart-connect-js/src/components/InstallPrompt.jsx, bulak-smart-connect-js/src/hooks/usePWA.js, bulak-smart-connect-js/src/main.jsx
Improve the PWA installation experience by adding enhanced debugging information, automatically displaying the installation prompt, and ensuring service worker registration occurs before app rendering. This update aims to streamline the installation process and provide better user guidance.
=> Enhance PWA installation process with improved debugging and automatic prompt display

bulak-smart-connect-js/package.json, bulak-smart-connect-js/public/_headers, bulak-smart-connect-js/public/sw-handler.js, bulak-smart-connect-js/scripts/build-hook.js, bulak-smart-connect-js/src/App.jsx, bulak-smart-connect-js/src/components/UpdateNotification.jsx, bulak-smart-connect-js/src/hooks/usePWA.js, bulak-smart-connect-js/src/main.jsx, bulak-smart-connect-js/src/utils/version.js, bulak-smart-connect-js/vite.config.js
Improve user interaction with the PWA installation prompt and implement service worker auto-update, cache busting, and versioning support for better performance and user experience.
=> Refactor PWA installation and enhance functionality

bulak-smart-connect-js/vite.config.js
Improve the caching strategy by adding specific patterns for images and creating a dedicated cache for image files.
=> Enhance caching strategy in service worker for images

bsc-js-backend/src/auth/auth.service.ts, bsc-js-backend/src/users/users.controller.ts
Implement environment-configured bcrypt rounds and a centralized password hashing method to enhance security and maintainability in the authentication process. Additionally, merge updates from the main branch.
=> Refactor password hashing for improved security
